<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="P5-H7VQX52" name="org.SeleniumMaven.NewTest" tests="10" failures="0" timestamp="16 May 2018 09:05:20 GMT" time="0.052" errors="1">
  <testcase name="test1_2" time="0.003" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="test1_1" time="0.003" classname="org.SeleniumMaven.NewTest">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at org.SeleniumMaven.NewTest.test1_1(NewTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test1_1 -->
  <testcase name="Test3" time="0.005" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="test1_3" time="0.004" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="Test3" time="0.009" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="test1_3" time="0.006" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="Test3" time="0.006" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="Test3" time="0.008" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="test1_3" time="0.002" classname="org.SeleniumMaven.NewTest"/>
  <testcase name="test1_3" time="0.006" classname="org.SeleniumMaven.NewTest"/>
</testsuite> <!-- org.SeleniumMaven.NewTest -->
